# Generated by Django 6.0.1 on 2026-01-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libreria', models.CharField(max_length=100, unique=True)),
                ('direccion_fisica', models.CharField(max_length=50)),
                ('numero_estantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('cargo_mensual', models.CharField(max_length=25)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=4)),
                ('libreria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='Libreria.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=100)),
                ('autor_principal', models.CharField(max_length=100)),
                ('genero_literario', models.CharField(max_length=50)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('numero_paginas', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='Libreria.empleado')),
            ],
        ),
    ]
