# Generated by Django 6.0.1 on 2026-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cargo_mensual',
            new_name='cargo_empleado',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_mensual',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
