# Generated by Django 6.0.1 on 2026-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0002_rename_cargo_mensual_empleado_cargo_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
